version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/services/virtual-assistant/"
      - "/services/watson-extension/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
