version: '3.1'
services:
  postgres:
    image: quay.io/sclorg/postgresql-15-c9s:latest
    restart: always
    environment:
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_USER: ${DB_USERNAME}
      POSTGRESQL_DATABASE: ${DB_NAME}
    ports:
        - "5432:${DB_PORT}"
