version: 1
disable_existing_loggers: false
formatters:
  va_formatter:
    class: common.logging.VirtualAssistantLogFormatter
handlers:
  va_handler:
    formatter: va_formatter
    class: logging.StreamHandler
loggers:
  root:
    handlers: [va_handler]
  rasa:
    handlers: [va_handler]
    propagate: 0
