FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

USER root

ENV PYTHON_VERSION=3.9 \
    LANG=en_US.UTF-8 \
    PIP_NO_CACHE_DIR=off \
    PIPENV_VENV_IN_PROJECT=1 \
    PIPENV_VERBOSITY=-1 \
    APP_ROOT=/opt/virtual-assistant

# install postgresql from postgresql.org
RUN rpm -Uvh https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

RUN microdnf repolist
RUN microdnf repoquery  --available | grep postgresql15

RUN cat /var/log/dnf.log
RUN cat /etc/yum.repos.d/pgdg-redhat-all.repo
RUN curl https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-8-x86_64/  | grep postgresql15
RUN rpm -i https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-8-x86_64/postgresql15-15.7-3PGDG.rhel8.x86_64.rpm
