---
apiVersion: v1
kind: Template
metadata:
  name: virtual-assistant
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: virtual-assistant
  spec:
    envName: ${ENV_NAME}

    database:
      name: virtual-assistant
      version: 12

    deployments:
    - name: api
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
        metrics:
          enabled: true
      podSpec:
        image: ${API_IMAGE_NAME}:${API_IMAGE_TAG}
        command:
          - ./scripts/entrypoint.sh
          - api
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 27
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: ${API_CPU_LIMIT}
            memory: ${API_MEMORY_LIMIT}
          requests:
            cpu: ${API_CPU_REQUEST}
            memory: ${API_MEMORY_REQUEST}
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: TRACKER_STORE_TYPE
            value: ${TRACKER_STORE_TYPE}
          - name: PROMETHEUS
            value: ${PROMETHEUS}

    - name: actions
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
        metrics:
          enabled: true
      podSpec:
        image: ${ACTIONS_IMAGE_NAME}:${ACTIONS_IMAGE_TAG}
        command:
          - ./scripts/entrypoint.sh
          - actions
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 27
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: ${ACTIONS_CPU_LIMIT}
            memory: ${ACTIONS_MEMORY_LIMIT}
          requests:
            cpu: ${ACTIONS_CPU_REQUEST}
            memory: ${ACTIONS_MEMORY_REQUEST}
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: TRACKER_STORE_TYPE
            value: ${TRACKER_STORE_TYPE}
          - name: PROMETHEUS
            value: ${PROMETHEUS}

parameters:
- description: Minimum number of replicas required
  name: MIN_REPLICAS
  value: "1"
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: API_CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: API_MEMORY_LIMIT
  value: 2Gi
- description: cpu request of service
  name: API_CPU_REQUEST
  value: 250m
- description: memory request of service
  name: API_MEMORY_REQUEST
  value: 512Mi
- description: Cpu limit of service
  name: ACTIONS_CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: ACTIONS_MEMORY_LIMIT
  value: 512Mi
- description: cpu request of service
  name: ACTIONS_CPU_REQUEST
  value: 250m
- description: memory request of service
  name: ACTIONS_MEMORY_REQUEST
  value: 256Mi
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  value: "virtual-assistant"
  required: true
- descripton: Virtual Assistant API image name
  name: API_IMAGE_NAME
  value: "quay.io/cloudservices/virtual-assistant-api"
- description: API Image tag
  name: API_IMAGE_TAG
  required: true
- descripton: Virtual Assistant actions server image name
  name: ACTIONS_IMAGE_NAME
  value: "quay.io/cloudservices/virtual-assistant-actions"
- description: Actions Image tag
  name: ACTIONS_IMAGE_TAG
  required: true
- description: Tracker store type
  name: TRACKER_STORE_TYPE
  value: "SQL"
- description: Enable Prometheus
  name: PROMETHEUS
  value: "True"
