---
apiVersion: v1
kind: Template
metadata:
  name: virtual-assistant-v2
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: virtual-assistant
  spec:
    envName: ${ENV_NAME}
    optionalDependencies:
      - advisor-backend

    inMemoryDb: true
    deployments:
    - name: api
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
          apiPath: virtual-assistant
        metrics:
          enabled: true
      podSpec:
        image: ${API_IMAGE_NAME}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/virtual-assistant/v2/health/status
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/virtual-assistant/v2/health/status
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: LOGGER_TYPE
            value: ${LOGGER_TYPE}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: PROMETHEUS
            value: ${PROMETHEUS}
          - name: SERVER_REQUEST_MAX_HEADER_SIZE
            value: ${SERVER_REQUEST_MAX_HEADER_SIZE}
          - name: ENVIRONMENT_NAME
            value: ${ENVIRONMENT_NAME}
          - name: CONSOLEDOT_BASE_URL
            value: ${CONSOLEDOT_BASE_URL}
          - name: SESSION_STORAGE
            value: ${SESSION_STORAGE}
          - name: WATSON_API_URL
            valueFrom:
              secretKeyRef:
                name: virtual-assistant-watson
                key: api.url
          - name: WATSON_API_KEY
            valueFrom:
              secretKeyRef:
                name: virtual-assistant-watson
                key: api.key
          - name: WATSON_ENV_ID
            value: ${WATSON_ENV_ID}
          - name: WATSON_ENV_VERSION
            value: ${WATSON_ENV_VERSION}
        resources:
          limits:
            cpu: 250m
            memory: 120Mi
          requests:
            cpu: 100m
            memory: 80Mi
    - name: watson-extension
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
          apiPath: virtual-assistant-watson-extension
        metrics:
          enabled: true
      podSpec:
        image: ${WATSON_EXTENSION_IMAGE_NAME}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/virtual-assistant-watson-extension/v2/health/status
            port: 10000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 27
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/virtual-assistant-watson-extension/v2/health/status
            port: 10000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: LOGGER_TYPE
            value: ${LOGGER_TYPE}
          - name: PROMETHEUS
            value: ${PROMETHEUS}
          - name: ENVIRONMENT_NAME
            value: ${ENVIRONMENT_NAME}
          - name: SESSION_STORAGE
            value: ${SESSION_STORAGE}
        resources:
          limits:
            cpu: 250m
            memory: 120Mi
          requests:
            cpu: 100m
            memory: 80Mi
parameters:
- description: Minimum number of replicas required
  name: MIN_REPLICAS
  value: "1"
- name: LOG_LEVEL
  value: INFO
- description: Logging strategy to use. (basic, cloudwatch)
  name: LOGGER_TYPE
  value: cloudwatch
- description: Session storage backend to use to share session data.
  name: SESSION_STORAGE
  value: redis
- description: Watson environment id to use.
  name: WATSON_ENV_ID
  required: true
- description: Version of the watson environment
  name: WATSON_ENV_VERSION
  value: 2024-08-25
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  value: "virtual-assistant"
  required: true
- descripton: Virtual Assistant API image name
  name: API_IMAGE_NAME
  value: "quay.io/redhat-services-prod/hcc-platex-services-tenant/virtual-assistant-api-v2"
- descripton: Virtual Assistant actions server image name
  name: WATSON_EXTENSION_IMAGE_NAME
  value: "quay.io/redhat-services-prod/hcc-platex-services-tenant/virtual-assistant-watson-extension"
- description: The Image tag
  name: IMAGE_TAG
  value: "latest"
- description: Enable Prometheus
  name: PROMETHEUS
  value: "True"
- description: ConsoleDot base url
  name: CONSOLEDOT_BASE_URL
  value: https://console.redhat.com
- description: Server's max allowed header size
  name: SERVER_REQUEST_MAX_HEADER_SIZE
  value: "20000"
- name: ENVIRONMENT_NAME
  description: The name of the environment. Needs to be either stage or prod
  value: "prod"
