[project]
name = "watson_extension"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "common",
    "aiohttp>=3.11.11",
    "requests>=2.32.3",
]

[tool.uv.sources]
common = { workspace = true }
