{
 "title": "Virtual Assistant (Astro)",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability SLO (>95%)",
   "type": "stat",
   "description": "The proportion of successful requests, as measured from the load balancer metrics. Any HTTP status other than 500–599 is considered successful.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1.00 - (sum(rate(api_3scale_gateway_api_status{status=\"5xx\",exported_service=\"virtual-assistant\"}[$__range:1m])) / sum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\"}[$__range:1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLO <500ms (>90%)",
   "type": "stat",
   "description": "The proportion of sufficiently fast requests, as measured from the load balancer metrics. \"Sufficiently fast” is defined as < 500 ms.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_bucket{le=\"0500.0\", exported_service=\"virtual-assistant\"}[$__range:1m])) / sum(rate(api_3scale_gateway_api_time_bucket{le=\"+Inf\", exported_service=\"virtual-assistant\"}[$__range:1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate SLO (<5%)",
   "type": "stat",
   "description": "The percentage of requests that result in an error or failure. Any HTTP status other than 400–599 is considered successful.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\", status=~\"4xx|5xx\"}[$__range:1m]))\n   /\nsum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\"}[$__range:1m])), 0.0001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLO <1000ms (>95%)",
   "type": "stat",
   "description": "The proportion of sufficiently fast requests, as measured from the load balancer metrics. \"Sufficiently fast” is defined as < 500 ms.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_bucket{le=\"1000.0\", exported_service=\"virtual-assistant\"}[$__range:1m])) / sum(rate(api_3scale_gateway_api_time_bucket{le=\"+Inf\", exported_service=\"virtual-assistant\"}[$__range:1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Rate of API requests measured in requests per second.",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\"}[$__range:1m]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\", status=\"4xx\"}[$__range:1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\", status=\"2xx\"}[$__range:1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\", status=\"5xx\"}[$__range:1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "gauge",
   "description": "Total number of requests for each status code",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(api_3scale_gateway_api_status{exported_service=\"virtual-assistant\", status=~\"2xx|4xx|5xx\"}[$__range:1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}