name: Dependabot follow up

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv
      - name: Run pipenv lock
        run: pipenv lock
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Follow-up on dependabot - pipenv lock
