name: Lint checks

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: make install-root
      - name: Run linter
        run: make lint
